import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Lang = 'nl' | 'en' | 'sr' | 'hi'

// ─── Dutch ────────────────────────────────────────────────────────────────────
const nl = {
  lang_nl: 'Nederlands', lang_en: 'English', lang_sr: 'Sranantongo', lang_hi: 'Sarnami',

  role_admin: 'Beheerder', role_owner: 'Eigenaar', role_helpdesk: 'Helpdesk',

  nav_overview: 'Overzicht', nav_dashboard: 'Dashboard', nav_reservations: 'Reserveringen',
  nav_beheer: 'Beheer', nav_activities: 'Activiteiten', nav_software: 'Software',
  nav_ai: 'AI assistent', nav_requests: 'Aanvragen', nav_assign: 'Toewijzen',
  nav_issues: 'Storingen', nav_control: 'Controle', nav_account: 'Mijn account',
  nav_logout: 'Uitloggen',

  status_available: 'Beschikbaar', status_reserved: 'Gereserveerd', status_in_use: 'In gebruik',
  status_in_control: 'In controle', status_defect: 'Defect',
  status_out_of_service: 'Buiten gebruik', status_missing: 'Vermist',

  res_requested: 'In behandeling', res_approved: 'Goedgekeurd', res_rejected: 'Afgewezen',

  save: 'Opslaan', saving: 'Opslaan…', cancel: 'Annuleren', add: 'Toevoegen',
  remove: 'Verwijderen', edit: 'Wijzig', close: 'Sluiten', confirm: 'Bevestigen',
  search: 'Zoeken', loading: 'Laden…', yes: 'Ja', no: 'Nee',
  optional: 'optioneel', no_results: 'Geen resultaten',
  select_user: 'Selecteer een gebruiker om verder te gaan',

  search_placeholder: 'Zoek laptop…', search_hint: 'Selecteer eerst een gebruiker',
  search_empty: 'Geen laptops gevonden',
  notifs: 'Notificaties', notif_all_read: 'Alles gelezen', notif_empty: 'Geen notificaties.',
  theme_to_dark: 'Schakel naar donker', theme_to_light: 'Schakel naar licht',
  menu_open: 'Open menu', menu_close: 'Sluit menu',
  widget_nothing: 'Niets op dit moment.', widget_pending: 'Wachten op keuring',
  widget_issues: 'Open storingen', widget_upcoming: 'Aankomend',
  sidebar_approved: 'Goedgekeurd', sidebar_awaiting: 'In afwachting',

  dash_title: 'Dashboard', dash_sub: 'Statistieken en bezetting',
  dash_total: 'Totaal laptops', dash_available: 'Beschikbaar', dash_in_use: 'In gebruik',
  dash_defect: 'Defect', dash_missing: 'Vermist', dash_oos: 'Buiten gebruik',
  dash_reservations: 'Reserveringen', dash_pending: 'In behandeling',
  dash_issues: 'Open storingen', dash_chart: 'Beschikbaarheid', dash_chart_sub: 'van laptops vrij',
  dash_no_access: 'Dit dashboard is alleen toegankelijk voor beheerders en helpdesk',

  ov_title: 'Overzicht', ov_sub: 'Alle laptops in het systeem',
  ov_add: '+ Laptop toevoegen', ov_empty: 'Geen laptops gevonden',
  ov_select_user: 'Selecteer een gebruiker in de navigatiebalk om verder te gaan',
  ov_merk: 'Merk / type *', ov_specs: 'Specificaties', ov_ram: 'RAM (GB)',
  ov_ports: 'Poorten & connectiviteit', ov_vga: 'VGA poort', ov_hdmi: 'HDMI poort',
  ov_wifi_present: 'Wi-Fi aanwezig', ov_wifi_conn: 'Wi-Fi verbonden',
  ov_hw_status: 'Hardware status', ov_keys: 'Alle toetsen werken',
  ov_camera: 'Camera werkt', ov_mic: 'Microfoon werkt',
  ov_drives: 'Schijven', ov_add_drive: '+ Schijf toevoegen',
  ov_no_drives: 'Nog geen schijven toegevoegd',
  ov_letter: 'Letter', ov_type: 'Type', ov_size: 'Grootte (GB)', ov_free: 'Vrije ruimte (GB)',
  ov_clear_filters: '✕ Wis filters', ov_save_status: 'Status opslaan',
  ov_new_status: 'Nieuwe status', ov_maint_log: 'Onderhoudslog',
  ov_defect_desc: 'Beschrijf het defect',
  ov_oos_warning: 'Let op: laptop wordt permanent op buiten gebruik gezet',
  ov_remaining: 'resterend', ov_workdays: 'werkdag(en) resterend',
  ov_cancel: '✕ Annuleren',

  res_title: 'Reserveringen', res_sub: 'Openstaande aanvragen beoordelen',
  res_no_access: 'Deze pagina is alleen toegankelijk voor beheerders',
  res_add: '+ Reservering aanmaken', res_empty: 'Geen openstaande aanvragen.',
  res_requester: 'Aanvrager', res_contact: 'Contact', res_date: 'Datum',
  res_location: 'Locatie', res_count: 'Aantal laptops', res_goal: 'Doel',
  res_extra: 'Extra info', res_reason: 'Reden *',
  res_approve: 'Goedkeuren', res_reject: 'Afwijzen',
  res_form_owner: 'Eigenaar *', res_form_activity: 'Activiteit *',
  res_form_start: 'Startdatum *', res_form_end: 'Einddatum *',
  res_form_count: 'Aantal laptops *', res_form_goal: 'Doel *',
  res_form_name: 'Naam eigenaar *', res_form_phone: 'Telefoonnummer eigenaar (optioneel)',
  res_form_extra: 'Extra informatie (optioneel)', res_form_submit: 'Reservering aanmaken',

  req_title: 'Aanvragen', req_sub: 'Laptops aanvragen voor een activiteit',
  req_new: '+ Nieuwe aanvraag',
  req_activity: 'Activiteit *', req_start: 'Startdatum *', req_end: 'Einddatum *',
  req_count: 'Aantal laptops *', req_goal: 'Doel van de aanvraag *',
  req_name: 'Uw naam *', req_phone: 'Telefoonnummer (optioneel)',
  req_extra: 'Onvoorziene relevante informatie (optioneel)',
  req_extra_placeholder: 'bijzonderheden, speciale vereisten…',
  req_submit: 'Aanvraag indienen', req_empty: 'Nog geen aanvragen ingediend.',
  req_available: 'beschikbare laptops', req_none_available: 'Geen laptops beschikbaar',
  req_helpdesk: 'Helpdesk wijst laptops toe…',
  req_success: 'Aanvraag ingediend. De beheerder beoordeelt dit binnen 3 werkdagen.',
  req_list: 'Lijst', req_agenda: 'Agenda',
  req_legend_req: 'Aangevraagd', req_legend_app: 'Goedgekeurd', req_legend_rej: 'Afgewezen',

  beh_title: 'Beheer', beh_sub: 'Laptops, accounts en bulk acties',
  beh_no_access: 'Deze pagina is alleen toegankelijk voor beheerders',
  beh_tab_retire: 'Uit beheer nemen', beh_tab_bulk: 'Bulk status',
  beh_tab_accounts: 'Accounts', beh_tab_audit: 'Audit log',
  beh_retire_warning: 'Let op: laptop wordt permanent op buiten gebruik gezet',
  beh_retire_confirm: 'Bevestig: uit beheer nemen', beh_retire_cancel: 'Annuleren',
  beh_retire_locked: 'Vergrendeld', beh_retire_done: 'Uit beheer',
  beh_bulk_all: 'Alle', beh_bulk_mixed: 'Gemengde statussen — selecteer één type',
  beh_bulk_deselect: 'Deselecteer', beh_bulk_new: '— Nieuwe status —',
  beh_bulk_apply: 'Toepassen', beh_bulk_selected: 'Geselecteerd',
  beh_acc_name: 'Naam *', beh_acc_username: 'Gebruikersnaam *',
  beh_acc_email: 'E-mailadres (optioneel)', beh_acc_password: 'Wachtwoord *',
  beh_acc_role: 'Rol *', beh_acc_admin_pw: 'Jouw wachtwoord * (vereist voor admin)',
  beh_acc_add: '+ Account aanmaken', beh_acc_save: 'Opslaan', beh_acc_create: 'Account aanmaken',
  beh_audit_title: 'Laatste 100 gebeurtenissen', beh_audit_export: '↓ Exporteer CSV',
  beh_audit_empty: 'Nog geen audit-events geregistreerd',

  ctrl_title: 'Controle na gebruik', ctrl_sub: 'Controleer laptops die zijn ingeleverd',
  ctrl_no_access: 'Deze pagina is alleen toegankelijk voor helpdeskmedewerkers',
  ctrl_p1: 'Deel 1 – Laptop hardware controleren', ctrl_p2: 'Deel 2 – Laptop optimaliseren',
  ctrl_p3: 'Deel 3 – Wi-Fi controleren', ctrl_p4: 'Deel 4 – Laptop testen',
  ctrl_s1: 'Schijf controleren (SSD of HDD)', ctrl_s2: 'Werkgeheugen (RAM) controleren',
  ctrl_s3: 'Opslagruimte controleren', ctrl_s4: "Opstartprogramma's controleren",
  ctrl_s5: 'Energie-instellingen aanpassen', ctrl_s6: 'Wi-Fi signaal meten',
  ctrl_s7: 'Ping test uitvoeren', ctrl_s8: 'Toetsenbord testen',
  ctrl_s9: 'Camera testen', ctrl_s10: 'Microfoon testen',
  ctrl_disk_type: 'Type schijf', ctrl_disk_size: 'Grootte schijf',
  ctrl_disk_faster: 'Welke schijf is sneller?', ctrl_ram_total: 'Hoeveel RAM heeft de laptop?',
  ctrl_ram_used: 'Hoeveel RAM wordt gebruikt?', ctrl_storage: 'Vrije ruimte op C:',
  ctrl_startup: "Programma's die uitgeschakeld kunnen worden",
  ctrl_energy: 'Energieplan ingesteld op High Performance?',
  ctrl_wifi_signal: 'Signaalsterkte (%)', ctrl_ping: 'Ping naar google.com (ms)',
  ctrl_keyboard: 'Werken alle toetsen?', ctrl_camera: 'Werkt de camera?',
  ctrl_mic: 'Werkt de microfoon?',
  ctrl_submit_ok: 'Indienen — alles OK', ctrl_submit_issues: 'Indienen — bevindingen',
  ctrl_fill: 'Vul verplichte velden in (*)',
  ctrl_history: 'Eerdere controles', ctrl_passed: 'Geslaagd', ctrl_failed: 'Niet geslaagd',

  tw_title: 'Laptops toewijzen', tw_sub: 'Wijs laptops toe aan goedgekeurde reserveringen',
  tw_no_access: 'Deze pagina is alleen toegankelijk voor helpdeskmedewerkers',
  tw_pending: 'Nog toe te wijzen', tw_assigned: 'Al toegewezen',
  tw_needed: 'laptops nodig', tw_open: '▼ Toewijzen', tw_close: '▲ Sluiten',
  tw_select_exact: 'Selecteer precies', tw_laptops: 'laptop(s)', tw_selected: 'geselecteerd',
  tw_no_avail: 'Geen beschikbare laptops', tw_submit: 'laptop(s) toewijzen',
  tw_done: 'Klaar', tw_empty: 'Alle goedgekeurde reserveringen hebben laptops toegewezen',
  tw_contact: 'Contact',

  acc_title: 'Mijn account', acc_change_pw: 'Wachtwoord veranderen',
  acc_guide: 'Handleiding & app installeren',
  acc_curr_pw: 'Huidig wachtwoord', acc_new_pw: 'Nieuw wachtwoord',
  acc_confirm_pw: 'Bevestig nieuw wachtwoord', acc_min: 'Minimaal 6 tekens',
  acc_save_pw: 'Wachtwoord wijzigen', acc_install_title: 'App toevoegen aan beginscherm',
  acc_install_desc: 'Installeer Laptopbeheer als app op je telefoon — geen app store nodig',
  acc_android: '🤖 Android', acc_ios: '🍎 iPhone / iPad (iOS)',
  acc_ios_note: 'Let op: gebruik Safari. Chrome op iOS ondersteunt dit niet',
}

// ─── English ──────────────────────────────────────────────────────────────────
const en: typeof nl = {
  lang_nl: 'Dutch', lang_en: 'English', lang_sr: 'Sranantongo', lang_hi: 'Sarnami',

  role_admin: 'Administrator', role_owner: 'Owner', role_helpdesk: 'Helpdesk',

  nav_overview: 'Overview', nav_dashboard: 'Dashboard', nav_reservations: 'Reservations',
  nav_beheer: 'Management', nav_activities: 'Activities', nav_software: 'Software',
  nav_ai: 'AI assistant', nav_requests: 'Requests', nav_assign: 'Assign',
  nav_issues: 'Issues', nav_control: 'Inspection', nav_account: 'My account',
  nav_logout: 'Log out',

  status_available: 'Available', status_reserved: 'Reserved', status_in_use: 'In use',
  status_in_control: 'In inspection', status_defect: 'Defective',
  status_out_of_service: 'Out of service', status_missing: 'Missing',

  res_requested: 'Pending', res_approved: 'Approved', res_rejected: 'Rejected',

  save: 'Save', saving: 'Saving…', cancel: 'Cancel', add: 'Add',
  remove: 'Remove', edit: 'Edit', close: 'Close', confirm: 'Confirm',
  search: 'Search', loading: 'Loading…', yes: 'Yes', no: 'No',
  optional: 'optional', no_results: 'No results',
  select_user: 'Select a user to continue',

  search_placeholder: 'Search laptop…', search_hint: 'Select a user first',
  search_empty: 'No laptops found',
  notifs: 'Notifications', notif_all_read: 'Mark all read', notif_empty: 'No notifications.',
  theme_to_dark: 'Switch to dark', theme_to_light: 'Switch to light',
  menu_open: 'Open menu', menu_close: 'Close menu',
  widget_nothing: 'Nothing at the moment.', widget_pending: 'Awaiting approval',
  widget_issues: 'Open issues', widget_upcoming: 'Upcoming',
  sidebar_approved: 'Approved', sidebar_awaiting: 'Awaiting',

  dash_title: 'Dashboard', dash_sub: 'Statistics and occupancy',
  dash_total: 'Total laptops', dash_available: 'Available', dash_in_use: 'In use',
  dash_defect: 'Defective', dash_missing: 'Missing', dash_oos: 'Out of service',
  dash_reservations: 'Reservations', dash_pending: 'Pending',
  dash_issues: 'Open issues', dash_chart: 'Availability', dash_chart_sub: 'of laptops free',
  dash_no_access: 'This dashboard is only accessible to administrators and helpdesk',

  ov_title: 'Overview', ov_sub: 'All laptops in the system',
  ov_add: '+ Add laptop', ov_empty: 'No laptops found',
  ov_select_user: 'Select a user in the navigation bar to continue',
  ov_merk: 'Brand / type *', ov_specs: 'Specifications', ov_ram: 'RAM (GB)',
  ov_ports: 'Ports & connectivity', ov_vga: 'VGA port', ov_hdmi: 'HDMI port',
  ov_wifi_present: 'Wi-Fi present', ov_wifi_conn: 'Wi-Fi connected',
  ov_hw_status: 'Hardware status', ov_keys: 'All keys work',
  ov_camera: 'Camera works', ov_mic: 'Microphone works',
  ov_drives: 'Drives', ov_add_drive: '+ Add drive',
  ov_no_drives: 'No drives added yet',
  ov_letter: 'Letter', ov_type: 'Type', ov_size: 'Size (GB)', ov_free: 'Free space (GB)',
  ov_clear_filters: '✕ Clear filters', ov_save_status: 'Save status',
  ov_new_status: 'New status', ov_maint_log: 'Maintenance log',
  ov_defect_desc: 'Describe the defect',
  ov_oos_warning: 'Warning: laptop will be permanently set to out of service',
  ov_remaining: 'remaining', ov_workdays: 'working day(s) remaining',
  ov_cancel: '✕ Cancel',

  res_title: 'Reservations', res_sub: 'Review pending requests',
  res_no_access: 'This page is only accessible to administrators',
  res_add: '+ Create reservation', res_empty: 'No pending requests.',
  res_requester: 'Requester', res_contact: 'Contact', res_date: 'Date',
  res_location: 'Location', res_count: 'Number of laptops', res_goal: 'Purpose',
  res_extra: 'Extra info', res_reason: 'Reason *',
  res_approve: 'Approve', res_reject: 'Reject',
  res_form_owner: 'Owner *', res_form_activity: 'Activity *',
  res_form_start: 'Start date *', res_form_end: 'End date *',
  res_form_count: 'Number of laptops *', res_form_goal: 'Purpose *',
  res_form_name: 'Owner name *', res_form_phone: 'Owner phone number (optional)',
  res_form_extra: 'Extra information (optional)', res_form_submit: 'Create reservation',

  req_title: 'Requests', req_sub: 'Request laptops for an activity',
  req_new: '+ New request',
  req_activity: 'Activity *', req_start: 'Start date *', req_end: 'End date *',
  req_count: 'Number of laptops *', req_goal: 'Purpose of the request *',
  req_name: 'Your name *', req_phone: 'Phone number (optional)',
  req_extra: 'Any other relevant information (optional)',
  req_extra_placeholder: 'special requirements, notes…',
  req_submit: 'Submit request', req_empty: 'No requests submitted yet.',
  req_available: 'available laptops', req_none_available: 'No laptops available',
  req_helpdesk: 'Helpdesk is assigning laptops…',
  req_success: 'Request submitted. The administrator will review this within 3 working days.',
  req_list: 'List', req_agenda: 'Calendar',
  req_legend_req: 'Requested', req_legend_app: 'Approved', req_legend_rej: 'Rejected',

  beh_title: 'Management', beh_sub: 'Laptops, accounts and bulk actions',
  beh_no_access: 'This page is only accessible to administrators',
  beh_tab_retire: 'Retire laptop', beh_tab_bulk: 'Bulk status',
  beh_tab_accounts: 'Accounts', beh_tab_audit: 'Audit log',
  beh_retire_warning: 'Warning: laptop will be permanently set to out of service',
  beh_retire_confirm: 'Confirm: retire laptop', beh_retire_cancel: 'Cancel',
  beh_retire_locked: 'Locked', beh_retire_done: 'Retired',
  beh_bulk_all: 'All', beh_bulk_mixed: 'Mixed statuses — select one type',
  beh_bulk_deselect: 'Deselect', beh_bulk_new: '— New status —',
  beh_bulk_apply: 'Apply', beh_bulk_selected: 'Selected',
  beh_acc_name: 'Name *', beh_acc_username: 'Username *',
  beh_acc_email: 'Email address (optional)', beh_acc_password: 'Password *',
  beh_acc_role: 'Role *', beh_acc_admin_pw: 'Your password * (required for admin)',
  beh_acc_add: '+ Create account', beh_acc_save: 'Save', beh_acc_create: 'Create account',
  beh_audit_title: 'Last 100 events', beh_audit_export: '↓ Export CSV',
  beh_audit_empty: 'No audit events recorded yet',

  ctrl_title: 'Post-use inspection', ctrl_sub: 'Inspect returned laptops',
  ctrl_no_access: 'This page is only accessible to helpdesk staff',
  ctrl_p1: 'Part 1 – Check laptop hardware', ctrl_p2: 'Part 2 – Optimise laptop',
  ctrl_p3: 'Part 3 – Check Wi-Fi', ctrl_p4: 'Part 4 – Test laptop',
  ctrl_s1: 'Check drive (SSD or HDD)', ctrl_s2: 'Check working memory (RAM)',
  ctrl_s3: 'Check storage space', ctrl_s4: 'Check startup programs',
  ctrl_s5: 'Adjust power settings', ctrl_s6: 'Measure Wi-Fi signal',
  ctrl_s7: 'Run ping test', ctrl_s8: 'Test keyboard',
  ctrl_s9: 'Test camera', ctrl_s10: 'Test microphone',
  ctrl_disk_type: 'Drive type', ctrl_disk_size: 'Drive size',
  ctrl_disk_faster: 'Which drive is faster?', ctrl_ram_total: 'How much RAM does the laptop have?',
  ctrl_ram_used: 'How much RAM is being used?', ctrl_storage: 'Free space on C:',
  ctrl_startup: 'Programs that can be disabled',
  ctrl_energy: 'Power plan set to High Performance?',
  ctrl_wifi_signal: 'Signal strength (%)', ctrl_ping: 'Ping to google.com (ms)',
  ctrl_keyboard: 'Do all keys work?', ctrl_camera: 'Does the camera work?',
  ctrl_mic: 'Does the microphone work?',
  ctrl_submit_ok: 'Submit — all OK', ctrl_submit_issues: 'Submit — with findings',
  ctrl_fill: 'Fill in required fields (*)',
  ctrl_history: 'Previous inspections', ctrl_passed: 'Passed', ctrl_failed: 'Failed',

  tw_title: 'Assign laptops', tw_sub: 'Assign laptops to approved reservations',
  tw_no_access: 'This page is only accessible to helpdesk staff',
  tw_pending: 'Still to be assigned', tw_assigned: 'Already assigned',
  tw_needed: 'laptops needed', tw_open: '▼ Assign', tw_close: '▲ Close',
  tw_select_exact: 'Select exactly', tw_laptops: 'laptop(s)', tw_selected: 'selected',
  tw_no_avail: 'No available laptops', tw_submit: 'laptop(s) assign',
  tw_done: 'Done', tw_empty: 'All approved reservations have laptops assigned',
  tw_contact: 'Contact',

  acc_title: 'My account', acc_change_pw: 'Change password',
  acc_guide: 'Guide & install app',
  acc_curr_pw: 'Current password', acc_new_pw: 'New password',
  acc_confirm_pw: 'Confirm new password', acc_min: 'At least 6 characters',
  acc_save_pw: 'Change password', acc_install_title: 'Add app to home screen',
  acc_install_desc: 'Install Laptopbeheer as an app on your phone — no app store needed',
  acc_android: '🤖 Android', acc_ios: '🍎 iPhone / iPad (iOS)',
  acc_ios_note: 'Note: use Safari. Chrome on iOS does not support this',
}

// ─── Sranantongo (Surinamese Creole) ──────────────────────────────────────────
// Sranan borrows heavily from Dutch/English for technical terms — this is authentic.
const sr: typeof nl = {
  lang_nl: 'Hollands', lang_en: 'Engels', lang_sr: 'Sranantongo', lang_hi: 'Sarnami',

  role_admin: 'Bigiman', role_owner: 'Eygi Sma', role_helpdesk: 'Helpdesk',

  nav_overview: 'Ala Laptop', nav_dashboard: 'Dashboard', nav_reservations: 'Reserveri',
  nav_beheer: 'Managi', nav_activities: 'Aktiviteti', nav_software: 'Software',
  nav_ai: 'AI Helpman', nav_requests: 'Begi', nav_assign: 'Gi Laptop',
  nav_issues: 'Kapoti', nav_control: 'Tyeki', nav_account: 'Mi Kontu',
  nav_logout: 'Go Na Baka',

  status_available: 'Fri', status_reserved: 'Gereserveri', status_in_use: 'Na Wroko',
  status_in_control: 'Na Tyeki', status_defect: 'Brokoe',
  status_out_of_service: 'Kba Kba', status_missing: 'Loisi',

  res_requested: 'Dey Luku', res_approved: 'Aksi Go', res_rejected: 'Wi Baka',

  save: 'Sabi', saving: 'Sabi…', cancel: 'Kanseri', add: 'Poti',
  remove: 'Teki Weki', edit: 'Tjengeri', close: 'Kosi', confirm: 'Ya Tru',
  search: 'Suku', loading: 'Ladi…', yes: 'Ya', no: 'Nono',
  optional: 'nanga wil', no_results: 'Niks feni',
  select_user: 'Fosi suku wan gebruiker fu go fesi',

  search_placeholder: 'Suku laptop…', search_hint: 'Fosi sori wan gebruiker',
  search_empty: 'Niks laptop feni',
  notifs: 'Berichten', notif_all_read: 'Ala lesi kba', notif_empty: 'Niks berichten.',
  theme_to_dark: 'Donkru kleur', theme_to_light: 'Leti kleur',
  menu_open: 'Opo menu', menu_close: 'Kosi menu',
  widget_nothing: 'Niks na dis moment.', widget_pending: 'Wacht na keuring',
  widget_issues: 'Kapoti opo', widget_upcoming: 'Kon na Fesi',
  sidebar_approved: 'Aksi Go', sidebar_awaiting: 'Wacht',

  dash_title: 'Dashboard', dash_sub: 'Tel nanga Laptop Situatie',
  dash_total: 'Ala Laptop', dash_available: 'Fri', dash_in_use: 'Na Wroko',
  dash_defect: 'Brokoe', dash_missing: 'Loisi', dash_oos: 'Kba Kba',
  dash_reservations: 'Reserveri', dash_pending: 'Dey Luku',
  dash_issues: 'Kapoti Opo', dash_chart: 'Fri Laptop', dash_chart_sub: 'laptop fri',
  dash_no_access: 'Dis dashboard na fu bigiman nanga helpdesk nomo',

  ov_title: 'Ala Laptop', ov_sub: 'Ala laptop na den systema',
  ov_add: '+ Poti Laptop', ov_empty: 'Niks laptop feni',
  ov_select_user: 'Fosi sori wan gebruiker fu go fesi',
  ov_merk: 'Merk / type *', ov_specs: 'Spesifikasi', ov_ram: 'RAM (GB)',
  ov_ports: 'Poorten nanga verbinding', ov_vga: 'VGA poort', ov_hdmi: 'HDMI poort',
  ov_wifi_present: 'Wi-Fi de', ov_wifi_conn: 'Wi-Fi verbinden kba',
  ov_hw_status: 'Hardware situatie', ov_keys: 'Ala toetsen wroko',
  ov_camera: 'Camera wroko', ov_mic: 'Microfoon wroko',
  ov_drives: 'Schijven', ov_add_drive: '+ Poti Schijf',
  ov_no_drives: 'Niks schijf poti ete',
  ov_letter: 'Letter', ov_type: 'Type', ov_size: 'Grootte (GB)', ov_free: 'Fri Pasi (GB)',
  ov_clear_filters: '✕ Wisi Filters', ov_save_status: 'Sabi Situatie',
  ov_new_status: 'Nyun Situatie', ov_maint_log: 'Onderhoud Skrifi',
  ov_defect_desc: 'Taki san brokoe',
  ov_oos_warning: 'Luku bun: laptop e go kba kba permanently',
  ov_remaining: 'resti', ov_workdays: 'werkdag(en) resti',
  ov_cancel: '✕ Kanseri',

  res_title: 'Reserveri', res_sub: 'Tyeki den begi fu aksi of wi',
  res_no_access: 'Dis pesi na fu bigiman nomo',
  res_add: '+ Meki Reservering', res_empty: 'Niks begi de.',
  res_requester: 'Aksi Sma', res_contact: 'Kontakt', res_date: 'Dati',
  res_location: 'Pesi', res_count: 'Numro Laptop', res_goal: 'Fu San',
  res_extra: 'Moro Tori', res_reason: 'Reden *',
  res_approve: 'Aksi Go', res_reject: 'Wi Baka',
  res_form_owner: 'Eygi Sma *', res_form_activity: 'Aktiviteit *',
  res_form_start: 'Bigin Dati *', res_form_end: 'Einde Dati *',
  res_form_count: 'Numro Laptop *', res_form_goal: 'Fu San *',
  res_form_name: 'Nen Eygi Sma *', res_form_phone: 'Telefon Numro (nanga wil)',
  res_form_extra: 'Moro Tori (nanga wil)', res_form_submit: 'Meki Reservering',

  req_title: 'Begi', req_sub: 'Begi laptop fu wan aktiviteit',
  req_new: '+ Nyun Begi',
  req_activity: 'Aktiviteit *', req_start: 'Bigin Dati *', req_end: 'Einde Dati *',
  req_count: 'Numro Laptop *', req_goal: 'Fu san yu wani den laptop *',
  req_name: 'Yu Nen *', req_phone: 'Telefon Numro (nanga wil)',
  req_extra: 'Moro Tori (nanga wil)',
  req_extra_placeholder: 'spesial sani, wensen…',
  req_submit: 'Seni Begi', req_empty: 'Niks begi seni ete.',
  req_available: 'laptop fri', req_none_available: 'Niks laptop fri',
  req_helpdesk: 'Helpdesk e gi laptop…',
  req_success: 'Begi seni kba. Bigiman e tyeki dis na 3 werkdagen.',
  req_list: 'Listi', req_agenda: 'Agenda',
  req_legend_req: 'Begi', req_legend_app: 'Aksi Go', req_legend_rej: 'Wi Baka',

  beh_title: 'Managi', beh_sub: 'Laptop, kontu nanga bulk aksi',
  beh_no_access: 'Dis pesi na fu bigiman nomo',
  beh_tab_retire: 'Teki Laptop Na Baka', beh_tab_bulk: 'Bulk Situatie',
  beh_tab_accounts: 'Kontu', beh_tab_audit: 'Audit log',
  beh_retire_warning: 'Luku bun: laptop e go kba kba permanently',
  beh_retire_confirm: 'Konfirm: Teki Laptop Na Baka', beh_retire_cancel: 'Kanseri',
  beh_retire_locked: 'Grendel', beh_retire_done: 'Kba',
  beh_bulk_all: 'Ala', beh_bulk_mixed: 'Miks situatie — soru wan type',
  beh_bulk_deselect: 'Deselecteer', beh_bulk_new: '— Nyun Situatie —',
  beh_bulk_apply: 'Doro', beh_bulk_selected: 'Sori kba',
  beh_acc_name: 'Nen *', beh_acc_username: 'Gebruikersnaam *',
  beh_acc_email: 'E-mail (nanga wil)', beh_acc_password: 'Wachtwoord *',
  beh_acc_role: 'Rol *', beh_acc_admin_pw: 'Yu wachtwoord * (vereis fu admin)',
  beh_acc_add: '+ Meki Kontu', beh_acc_save: 'Sabi', beh_acc_create: 'Meki Kontu',
  beh_audit_title: 'Laste 100 Sani Pasa', beh_audit_export: '↓ Download CSV',
  beh_audit_empty: 'Niks audit-event skrifi ete',

  ctrl_title: 'Tyeki Baka Na Gebruiki', ctrl_sub: 'Tyeki laptop di kon baka',
  ctrl_no_access: 'Dis pesi na fu helpdesksma nomo',
  ctrl_p1: 'Deel 1 – Tyeki Laptop Hardware', ctrl_p2: 'Deel 2 – Bun Meki Laptop',
  ctrl_p3: 'Deel 3 – Tyeki Wi-Fi', ctrl_p4: 'Deel 4 – Tesi Laptop',
  ctrl_s1: 'Tyeki Schijf (SSD of HDD)', ctrl_s2: 'Tyeki Werkgeheugen (RAM)',
  ctrl_s3: 'Tyeki Opslagruimte', ctrl_s4: 'Tyeki Opstart Programma',
  ctrl_s5: 'Seti Energie Plan', ctrl_s6: 'Miti Wi-Fi Signaal',
  ctrl_s7: 'Drai Ping Test', ctrl_s8: 'Tesi Toetsenbord',
  ctrl_s9: 'Tesi Camera', ctrl_s10: 'Tesi Microfoon',
  ctrl_disk_type: 'Type Schijf', ctrl_disk_size: 'Grootte Schijf',
  ctrl_disk_faster: 'San Schijf Moro Faste?', ctrl_ram_total: 'Opo Much RAM a laptop abi?',
  ctrl_ram_used: 'Opo Much RAM e weri?', ctrl_storage: 'Fri Pasi na C:',
  ctrl_startup: 'Programma di man poti doro',
  ctrl_energy: 'Energieplan seti na High Performance?',
  ctrl_wifi_signal: 'Signaal Sterkte (%)', ctrl_ping: 'Ping na google.com (ms)',
  ctrl_keyboard: 'Ala toetsen wroko?', ctrl_camera: 'Camera wroko?',
  ctrl_mic: 'Microfoon wroko?',
  ctrl_submit_ok: 'Seni — Ala Bun', ctrl_submit_issues: 'Seni — Nanga Feni',
  ctrl_fill: 'Vul verplichte velden in (*)',
  ctrl_history: 'Olo Tyeki', ctrl_passed: 'Pasi', ctrl_failed: 'No Pasi',

  tw_title: 'Gi Laptop', tw_sub: 'Gi laptop na den reservering di aksi go',
  tw_no_access: 'Dis pesi na fu helpdesksma nomo',
  tw_pending: 'Laptop No Gi Ete', tw_assigned: 'Laptop Gi Kba',
  tw_needed: 'laptop nodig', tw_open: '▼ Gi Laptop', tw_close: '▲ Kosi',
  tw_select_exact: 'Sori eksakt', tw_laptops: 'laptop(s)', tw_selected: 'sori kba',
  tw_no_avail: 'Niks laptop fri', tw_submit: 'laptop(s) gi',
  tw_done: 'Kba', tw_empty: 'Ala reservering abi laptop kba',
  tw_contact: 'Kontakt',

  acc_title: 'Mi Kontu', acc_change_pw: 'Tjengeri Wachtwoord',
  acc_guide: 'Handleiding nanga App',
  acc_curr_pw: 'Olo Wachtwoord', acc_new_pw: 'Nyun Wachtwoord',
  acc_confirm_pw: 'Konfirm Nyun Wachtwoord', acc_min: 'Minst 6 letter',
  acc_save_pw: 'Tjengeri Wachtwoord', acc_install_title: 'Poti App na Fesi Scriin',
  acc_install_desc: 'Installeri Laptopbeheer na yu telefon — niks app store nodig',
  acc_android: '🤖 Android', acc_ios: '🍎 iPhone / iPad (iOS)',
  acc_ios_note: 'Luku bun: Gebruiki Safari. Chrome na iOS no kan disi',
}

// ─── Sarnami Hindi (Surinamese Hindi, romanized) ──────────────────────────────
const hi: typeof nl = {
  lang_nl: 'Hollands', lang_en: 'Angreji', lang_sr: 'Sranantongo', lang_hi: 'Sarnami',

  role_admin: 'Prabandhak', role_owner: 'Malik', role_helpdesk: 'Helpdesk',

  nav_overview: 'Sab Laptop', nav_dashboard: 'Dashboard', nav_reservations: 'Bukking',
  nav_beheer: 'Intazam', nav_activities: 'Karyakram', nav_software: 'Software',
  nav_ai: 'AI Sahayak', nav_requests: 'Darhwast', nav_assign: 'Laptop De',
  nav_issues: 'Kharaabi', nav_control: 'Jaanch', nav_account: 'Mera Khaata',
  nav_logout: 'Bahar Jao',

  status_available: 'Uplabdh', status_reserved: 'Bukki Hai', status_in_use: 'Istemal Mein',
  status_in_control: 'Jaanch Mein', status_defect: 'Kharaab',
  status_out_of_service: 'Band Hai', status_missing: 'Kho Gaya',

  res_requested: 'Intazar Mein', res_approved: 'Manjoor', res_rejected: 'Nakaara',

  save: 'Bachao', saving: 'Bachao…', cancel: 'Ruk Jao', add: 'Joro',
  remove: 'Hatao', edit: 'Badlo', close: 'Band Karo', confirm: 'Pakka Karo',
  search: 'Dhoondho', loading: 'Lad raha hai…', yes: 'Haan', no: 'Nahi',
  optional: 'optional', no_results: 'Kuch nahi mila',
  select_user: 'Aage badhne ke liye ek user chunna',

  search_placeholder: 'Laptop dhoondho…', search_hint: 'Pehle ek user chunna',
  search_empty: 'Koi laptop nahi mila',
  notifs: 'Suchanaa', notif_all_read: 'Sab padh liya', notif_empty: 'Koi suchanaa nahi.',
  theme_to_dark: 'Andhera Rang', theme_to_light: 'Ujala Rang',
  menu_open: 'Menu Kholo', menu_close: 'Menu Band Karo',
  widget_nothing: 'Abhi kuch nahi.', widget_pending: 'Jaanch ka Intazar',
  widget_issues: 'Khuli Kharaabi', widget_upcoming: 'Aane Wala',
  sidebar_approved: 'Manjoor', sidebar_awaiting: 'Intazar Mein',

  dash_title: 'Dashboard', dash_sub: 'Aankda aur Laptop Haal',
  dash_total: 'Sab Laptop', dash_available: 'Uplabdh', dash_in_use: 'Istemal Mein',
  dash_defect: 'Kharaab', dash_missing: 'Kho Gaya', dash_oos: 'Band Hai',
  dash_reservations: 'Bukking', dash_pending: 'Intazar Mein',
  dash_issues: 'Khuli Kharaabi', dash_chart: 'Uplabdhata', dash_chart_sub: 'laptop khali hai',
  dash_no_access: 'Yeh dashboard sirf prabandhak aur helpdesk ke liye hai',

  ov_title: 'Sab Laptop', ov_sub: 'Sisteema mein sab laptop',
  ov_add: '+ Laptop Joro', ov_empty: 'Koi laptop nahi mila',
  ov_select_user: 'Aage badhne ke liye navigation mein user chunna',
  ov_merk: 'Brand / type *', ov_specs: 'Visheshata', ov_ram: 'RAM (GB)',
  ov_ports: 'Ports aur connection', ov_vga: 'VGA port', ov_hdmi: 'HDMI port',
  ov_wifi_present: 'Wi-Fi maujood hai', ov_wifi_conn: 'Wi-Fi jura hua hai',
  ov_hw_status: 'Hardware haal', ov_keys: 'Sab keys kaam karte hain',
  ov_camera: 'Camera kaam karta hai', ov_mic: 'Microfoon kaam karta hai',
  ov_drives: 'Drives', ov_add_drive: '+ Drive Joro',
  ov_no_drives: 'Abhi koi drive nahi jura',
  ov_letter: 'Letter', ov_type: 'Kisam', ov_size: 'Saaiz (GB)', ov_free: 'Khaali Jagah (GB)',
  ov_clear_filters: '✕ Filter Hatao', ov_save_status: 'Haal Bachao',
  ov_new_status: 'Naya Haal', ov_maint_log: 'Sudhaar Log',
  ov_defect_desc: 'Kharaabi batao',
  ov_oos_warning: 'Dhyan do: laptop hamesha ke liye band ho jayega',
  ov_remaining: 'bacha hai', ov_workdays: 'kaam ke din bacha hai',
  ov_cancel: '✕ Ruk Jao',

  res_title: 'Bukking', res_sub: 'Darhwast ko manjoor ya nakaaro',
  res_no_access: 'Yeh panna sirf prabandhak ke liye hai',
  res_add: '+ Bukking Banao', res_empty: 'Koi darhwast nahi hai.',
  res_requester: 'Maangne Wala', res_contact: 'Sampark', res_date: 'Tariikh',
  res_location: 'Jagah', res_count: 'Laptop Ginti', res_goal: 'Maqsad',
  res_extra: 'Aur Jaankari', res_reason: 'Wajah *',
  res_approve: 'Manjoor Karo', res_reject: 'Nakaar Do',
  res_form_owner: 'Malik *', res_form_activity: 'Karyakram *',
  res_form_start: 'Shuru Tariikh *', res_form_end: 'Khatam Tariikh *',
  res_form_count: 'Laptop Ginti *', res_form_goal: 'Maqsad *',
  res_form_name: 'Malik ka Naam *', res_form_phone: 'Phone Nambar (optional)',
  res_form_extra: 'Aur Jaankari (optional)', res_form_submit: 'Bukking Banao',

  req_title: 'Darhwast', req_sub: 'Karyakram ke liye laptop maango',
  req_new: '+ Naya Darhwast',
  req_activity: 'Karyakram *', req_start: 'Shuru Tariikh *', req_end: 'Khatam Tariikh *',
  req_count: 'Laptop Ginti *', req_goal: 'Darhwast ka Maqsad *',
  req_name: 'Aapka Naam *', req_phone: 'Phone Nambar (optional)',
  req_extra: 'Koi aur zaroori baat (optional)',
  req_extra_placeholder: 'khaas zaroorat, suchna…',
  req_submit: 'Darhwast Bhejo', req_empty: 'Abhi koi darhwast nahi bheji.',
  req_available: 'uplabdh laptop', req_none_available: 'Koi laptop uplabdh nahi',
  req_helpdesk: 'Helpdesk laptop de raha hai…',
  req_success: 'Darhwast bhej di. Prabandhak 3 kaam ke din mein dekh lega.',
  req_list: 'Suchi', req_agenda: 'Agenda',
  req_legend_req: 'Maanga Hai', req_legend_app: 'Manjoor', req_legend_rej: 'Nakaara',

  beh_title: 'Intazam', beh_sub: 'Laptop, khaata aur bulk kaam',
  beh_no_access: 'Yeh panna sirf prabandhak ke liye hai',
  beh_tab_retire: 'Laptop Hatao', beh_tab_bulk: 'Bulk Haal',
  beh_tab_accounts: 'Khaata', beh_tab_audit: 'Audit Log',
  beh_retire_warning: 'Dhyan do: laptop hamesha ke liye band ho jayega',
  beh_retire_confirm: 'Pakka: Laptop Hatao', beh_retire_cancel: 'Ruk Jao',
  beh_retire_locked: 'Tala Laga', beh_retire_done: 'Hataya Gaya',
  beh_bulk_all: 'Sab', beh_bulk_mixed: 'Mishal haal — ek type chunna',
  beh_bulk_deselect: 'Hatao Chunna', beh_bulk_new: '— Naya Haal —',
  beh_bulk_apply: 'Lagao', beh_bulk_selected: 'Chuna Hua',
  beh_acc_name: 'Naam *', beh_acc_username: 'Gebruikersnaam *',
  beh_acc_email: 'Email (optional)', beh_acc_password: 'Password *',
  beh_acc_role: 'Rol *', beh_acc_admin_pw: 'Aapka password * (admin ke liye zaroori)',
  beh_acc_add: '+ Khaata Banao', beh_acc_save: 'Bachao', beh_acc_create: 'Khaata Banao',
  beh_audit_title: 'Aakhri 100 Kaam', beh_audit_export: '↓ CSV Download Karo',
  beh_audit_empty: 'Abhi koi audit event nahi likha',

  ctrl_title: 'Istemal ke Baad Jaanch', ctrl_sub: 'Wapas aaye laptop ki jaanch karo',
  ctrl_no_access: 'Yeh panna sirf helpdesk ke liye hai',
  ctrl_p1: 'Hissa 1 – Laptop Hardware Jaancho', ctrl_p2: 'Hissa 2 – Laptop Theek Karo',
  ctrl_p3: 'Hissa 3 – Wi-Fi Jaancho', ctrl_p4: 'Hissa 4 – Laptop Test Karo',
  ctrl_s1: 'Drive Jaancho (SSD ya HDD)', ctrl_s2: 'Kaam ka Dhaaran (RAM) Jaancho',
  ctrl_s3: 'Jagah Jaancho', ctrl_s4: 'Shuru hone wale program jaancho',
  ctrl_s5: 'Bijli ka Plan Badlo', ctrl_s6: 'Wi-Fi Signal Napo',
  ctrl_s7: 'Ping Test Chalao', ctrl_s8: 'Keyboard Test Karo',
  ctrl_s9: 'Camera Test Karo', ctrl_s10: 'Microfoon Test Karo',
  ctrl_disk_type: 'Drive Kisam', ctrl_disk_size: 'Drive Saaiz',
  ctrl_disk_faster: 'Kaun sa drive zyada tej hai?', ctrl_ram_total: 'Laptop mein kitna RAM hai?',
  ctrl_ram_used: 'Kitna RAM istemal ho raha hai?', ctrl_storage: 'C: mein khaali jagah',
  ctrl_startup: 'Program jo band kiye ja sakte hain',
  ctrl_energy: 'Bijli plan High Performance par lagaya hai?',
  ctrl_wifi_signal: 'Signal Mazbooti (%)', ctrl_ping: 'Ping google.com par (ms)',
  ctrl_keyboard: 'Sab keys kaam karti hain?', ctrl_camera: 'Camera kaam karta hai?',
  ctrl_mic: 'Microfoon kaam karta hai?',
  ctrl_submit_ok: 'Bhejo — Sab Theek', ctrl_submit_issues: 'Bhejo — Kuch Mila',
  ctrl_fill: 'Zaroori khaane bharo (*)',
  ctrl_history: 'Pehli Jaanch', ctrl_passed: 'Paas', ctrl_failed: 'Fail',

  tw_title: 'Laptop Do', tw_sub: 'Manjoor bukking ko laptop do',
  tw_no_access: 'Yeh panna sirf helpdesk ke liye hai',
  tw_pending: 'Laptop Dena Baaki', tw_assigned: 'Laptop De Diya',
  tw_needed: 'laptop chahiye', tw_open: '▼ Laptop Do', tw_close: '▲ Band Karo',
  tw_select_exact: 'Bilkul itne chuno', tw_laptops: 'laptop', tw_selected: 'chuna gaya',
  tw_no_avail: 'Koi laptop uplabdh nahi', tw_submit: 'laptop de do',
  tw_done: 'Ho Gaya', tw_empty: 'Sab manjoor bukking ko laptop mil gaya',
  tw_contact: 'Sampark',

  acc_title: 'Mera Khaata', acc_change_pw: 'Password Badlo',
  acc_guide: 'Maargdarshan aur App',
  acc_curr_pw: 'Purana Password', acc_new_pw: 'Naya Password',
  acc_confirm_pw: 'Naya Password Pakka Karo', acc_min: 'Kam se kam 6 akshar',
  acc_save_pw: 'Password Badlo', acc_install_title: 'App Ghar Sciin par Lagao',
  acc_install_desc: 'Laptopbeheer apne phone par app jaise lagao — koi app store nahi chahiye',
  acc_android: '🤖 Android', acc_ios: '🍎 iPhone / iPad (iOS)',
  acc_ios_note: 'Dhyan do: Safari istemal karo. Chrome iOS par yeh nahi karta',
}

// ─── Context ──────────────────────────────────────────────────────────────────
const all = { nl, en, sr, hi } as const

type TranslationKey = keyof typeof nl
const LanguageContext = createContext<{
  lang: Lang
  setLang: (l: Lang) => void
  t: (k: TranslationKey) => string
}>({ lang: 'nl', setLang: () => {}, t: k => nl[k] })

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('nl')

  useEffect(() => {
    const saved = localStorage.getItem('asha_lang') as Lang | null
    if (saved && saved in all) setLangState(saved)
  }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('asha_lang', l)
  }

  const t = (k: TranslationKey) => all[lang][k] ?? nl[k]

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useT() {
  return useContext(LanguageContext)
}

export const LANG_OPTIONS: { code: Lang; flag: string; label: string }[] = [
  { code: 'nl', flag: '🇳🇱', label: 'Nederlands' },
  { code: 'en', flag: '🇬🇧', label: 'English' },
  { code: 'sr', flag: '🇸🇷', label: 'Sranantongo' },
  { code: 'hi', flag: '🇸🇷', label: 'Sarnami' },
]
